=== VadimVeremyev/EPAM_Lab_3/enrollees.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="enrollees">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="enrollee" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="firstName"/>
              <xs:element type="xs:string" name="middleName"/>
              <xs:element type="xs:string" name="lastName"/>
              <xs:element type="xs:string" name="facultyName"/>
              <xs:element type="xs:integer" name="id"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== VadimVeremyev/EPAM_Lab_3/751004.xml
<?xml version="1.0" encoding="UTF-8"?>
<enrollees xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" 
	xs:noNamespaceSchemaLocation="enrollees.xsd">
	<enrollee>
		<firstName>g</firstName>
		<middleName>g</middleName>
		<lastName>g</lastName>
		<facultyName>ITP</facultyName>
		<id>132070</id>
	</enrollee>
	
	<enrollee>
		<firstName>t</firstName>
		<middleName>t</middleName>
		<lastName>t</lastName>
		<facultyName>POIT</facultyName>
		<id>144979</id>
	</enrollee>

	<enrollee>
		<firstName>t</firstName>
		<middleName>t</middleName>
		<lastName>t</lastName>
		<facultyName>ITP</facultyName>
		<id>144979</id>
	</enrollee>
		
</enrollees>
